apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secret-provider
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.gcp.projectId }}/secrets/a-secrets/versions/latest"
        fileName: "apexsecrets.json"