replicaCount: 1

image:
  repository: us-east1-docker.pkg.dev/genial-union-452320-a6/apex/apexapp
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer  # Use NodePort if you prefer
  port: 3000

# env:
#   PORT: "3000"
#   DB_URL: "postgresql://apex_gcp_db_user:fkjBqF5GqYAbXK8ewwwXshdT8UeFcOG@dpg-cv2qatfnoe9s73b9m4fg-a.ohio-postgres.render.com/apex_gcp_db"

gcp:
  projectId: "genial-union-452320-a6"
  serviceAccount: "kubernetes"