name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main
env:
  GCP_PROJECT_ID: genial-union-452320-a6
  REGION: us-east1
  REPO: apex
  IMAGE_NAME: apexapp
  INSTANCE_NAME: my-test-engine     
  ZONE: us-east1-d          
  APP_PORT: 80:3000  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
         

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate Docker to Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image to Artifact Registry
        run: docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest


      - name: Deploy to Compute Engine
        run: |
          gcloud compute ssh ${{ env.INSTANCE_NAME }} \
            --zone ${{ env.ZONE }} \
            --command=" \
              docker pull ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest \
              && docker stop apex-app || true \
              && docker rm apex-app || true \
              && docker run -d --name apex-app -p ${{ env.APP_PORT }} ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest"