name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      # - main
env:
  GCP_PROJECT_ID: genial-union-452320-a6
  REGION: us-east1
  REPO: apex
  IMAGE_NAME: apexapp
  INSTANCE_NAME: apex-engine     
  ZONE: us-east1-d          
  APP_PORT: 3000:3000  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      # Debug step before building to verify source files
      - name: Debug repository content
        run: |
          echo "Current directory contents:"
          ls -la
          echo "entrypoint.sh content (local):"
          cat entrypoint.sh


      - name: Set up Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
         
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2


      - name: Authenticate Docker to Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and tag Docker image
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest -t ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:$BUILD_NUMBER .


      # Debug step after building to verify the presence of the entrypoint script
      - name: Verify Docker image contents
        run: |
          echo "Listing root directory:"
          docker run --rm ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest ls -la /
          
          echo "Listing /app directory:"
          docker run --rm ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest ls -la /app
          
          echo "Displaying /app/entrypoint.sh content:"
          docker run --rm --entrypoint cat ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest /app/entrypoint.sh



      - name: Push Docker image to Artifact Registry
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:$BUILD_NUMBER


      # - name: Deploy to Compute Engine
      #   run: |
      #     gcloud compute ssh ${{ env.INSTANCE_NAME }} \
      #       --zone ${{ env.ZONE }} \
      #       --command="gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev && \
      #         docker pull ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest && \
      #         docker stop apex-app || true && \
      #         docker rm apex-app || true && \
      #         docker run -d --name apex-app -p ${{ env.APP_PORT }} ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest"